# Generated by Django 5.1.4 on 2025-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful')], default='Pending', max_length=15),
        ),
    ]
