# Generated by Django 5.1.4 on 2025-01-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0002_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pickup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
