# Generated by Django 5.1.4 on 2025-01-26 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0003_receipt_proof_image_alter_receipt_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='sharebite.donation'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to=settings.AUTH_USER_MODEL),
        ),
    ]
