# Generated by Django 5.1.4 on 2025-05-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0005_dropofflocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
