# Generated by Django 5.2.17 on 2026-10-09 13:18

import django.db.models.deletion
from django.db import migrations, models


def seed_collection_points(apps, schema_editor):
    DropoffLocation = apps.get_model('sharebite', 'DropoffLocation')
    Donation = apps.get_model('sharebite', 'Donation')
    points = [
        {
            'name': 'Ancoats Share Hub',
            'address': '18 Demo Lane, Ancoats, Manchester',
            'latitude': 53.4840,
            'longitude': -2.2290,
            'opening_hours': 'Monday-Saturday, 9:00 AM-5:00 PM',
            'accepted_food_types': ['Fresh produce', 'Bakery', 'Packaged shelf-stable food'],
            'instructions': 'Hand donations to the staffed reception desk. Please keep chilled food in a cool bag.',
        },
        {
            'name': 'Hulme Community Pantry',
            'address': '7 Sample Gardens, Hulme, Manchester',
            'latitude': 53.4632,
            'longitude': -2.2496,
            'opening_hours': 'Monday-Friday, 10:00 AM-6:00 PM',
            'accepted_food_types': ['Fresh produce', 'Dairy', 'Packaged shelf-stable food'],
            'instructions': 'Use the community entrance and ask the on-duty pantry host to check in your donation.',
        },
        {
            'name': 'Salford Neighbourhood Kitchen',
            'address': '24 Example Street, Salford, Greater Manchester',
            'latitude': 53.4870,
            'longitude': -2.2933,
            'opening_hours': 'Tuesday-Sunday, 9:00 AM-4:00 PM',
            'accepted_food_types': ['Bakery', 'Packaged shelf-stable food', 'Fresh produce'],
            'instructions': 'Bring donations to the staffed side entrance. Label any allergens clearly.',
        },
    ]
    saved_points = []
    for point in points:
        saved, _ = DropoffLocation.objects.using(schema_editor.connection.alias).get_or_create(
            name=point['name'],
            defaults=point,
        )
        saved_points.append(saved)

    fallback = saved_points[0]
    Donation.objects.using(schema_editor.connection.alias).filter(
        collection_point__isnull=True,
    ).update(collection_point_id=fallback.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0006_alter_dropofflocation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='sharebite.dropofflocation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='collection_status',
            field=models.CharField(choices=[('awaiting_dropoff', 'Awaiting drop-off'), ('received_at_collection_point', 'Received at collection point')], default='awaiting_dropoff', max_length=40),
        ),
        migrations.AddField(
            model_name='dropofflocation',
            name='accepted_food_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dropofflocation',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dropofflocation',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(seed_collection_points, migrations.RunPython.noop),
    ]
