# Generated by Django 5.2.17 on 2026-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0008_require_donation_collection_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
