# Generated by Django 5.2.17 on 2026-10-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0009_donation_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
